import { PrismaClient, Role, DiscountType } from '@prisma/client';
import * as bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database...');

  // 1. Clean existing database
  await prisma.notification.deleteMany();
  await prisma.review.deleteMany();
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.cartItem.deleteMany();
  await prisma.cart.deleteMany();
  await prisma.wishlist.deleteMany();
  await prisma.address.deleteMany();
  await prisma.product.deleteMany();
  await prisma.category.deleteMany();
  await prisma.coupon.deleteMany();
  await prisma.user.deleteMany();

  // 2. Hash default passwords
  const hashedPassword = await bcrypt.hash('Password123', 10);

  // 3. Create test users
  const admin = await prisma.user.create({
    data: {
      name: 'SmartShop Admin',
      email: 'admin@smartshop.com',
      password: hashedPassword,
      role: Role.ADMIN,
      isVerified: true,
    },
  });

  const customer = await prisma.user.create({
    data: {
      name: 'John Doe',
      email: 'customer@smartshop.com',
      password: hashedPassword,
      role: Role.CUSTOMER,
      isVerified: true,
    },
  });

  // Create initial cart and wishlist for customer
  await prisma.cart.create({
    data: {
      userId: customer.id,
    },
  });

  await prisma.wishlist.create({
    data: {
      userId: customer.id,
    },
  });

  console.log('Created test users:', {
    admin: admin.email,
    customer: customer.email,
  });

  // 4. Create categories
  const categoriesData = [
    {
      name: 'Electronics',
      slug: 'electronics',
      image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=500&auto=format&fit=crop&q=60',
    },
    {
      name: 'Fashion',
      slug: 'fashion',
      image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=500&auto=format&fit=crop&q=60',
    },
    {
      name: 'Home & Kitchen',
      slug: 'home-kitchen',
      image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=500&auto=format&fit=crop&q=60',
    },
    {
      name: 'Books',
      slug: 'books',
      image: 'https://images.unsplash.com/photo-1495277490026-ac0588b02444?w=500&auto=format&fit=crop&q=60',
    },
    {
      name: 'Beauty',
      slug: 'beauty',
      image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=500&auto=format&fit=crop&q=60',
    },
  ];

  const categories: Record<string, any> = {};
  for (const cat of categoriesData) {
    const createdCat = await prisma.category.create({
      data: cat,
    });
    categories[createdCat.slug] = createdCat;
  }
  console.log('Created categories:', Object.keys(categories));

  // 5. Create products
  const rawProducts = [
    // AcousticPro (Electronics)
    {
      name: 'AcousticPro Studio ANC Headphones',
      description: 'Experience studio-grade sound with hybrid active noise cancellation, custom-tuned drivers, and 45-hour battery life.',
      price: 14999,
      discount: 10,
      stock: 25,
      brand: 'AcousticPro',
      images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80'],
      isFeatured: true,
      isTrending: true,
      categorySlug: 'electronics',
    },
    {
      name: 'AcousticPro Earbuds Pro',
      description: 'Ultra-lightweight true wireless earbuds featuring immersive bass, touch controls, and IPX7 sweat resistance.',
      price: 4999,
      discount: 15,
      stock: 45,
      brand: 'AcousticPro',
      images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80'],
      isFeatured: true,
      isTrending: false,
      categorySlug: 'electronics',
    },
    {
      name: 'AcousticPro Neckband Wireless',
      description: 'Ergonomic neckband wireless earphones with high fidelity sound, built-in mic, and quick charging.',
      price: 1999,
      discount: 5,
      stock: 60,
      brand: 'AcousticPro',
      images: ['https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: true,
      categorySlug: 'electronics',
    },
    {
      name: 'AcousticPro Bluetooth Speaker',
      description: 'Powerful 360-degree wireless speaker with dual passive radiators and colorful RGB sync lighting.',
      price: 3999,
      discount: 20,
      stock: 30,
      brand: 'AcousticPro',
      images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'electronics',
    },
    {
      name: 'AcousticPro Home Soundbar',
      description: 'Premium home theater soundbar with dedicated wireless subwoofer and Dolby Atmos compatibility.',
      price: 18999,
      discount: 12,
      stock: 15,
      brand: 'AcousticPro',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop&q=80'],
      isFeatured: true,
      isTrending: false,
      categorySlug: 'electronics',
    },
    {
      name: 'AcousticPro Gaming Headset',
      description: 'Immersive 7.1 surround sound headset with noise-isolating microphone and multi-platform compatibility.',
      price: 2999,
      discount: 0,
      stock: 40,
      brand: 'AcousticPro',
      images: ['https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: true,
      categorySlug: 'electronics',
    },
    {
      name: 'AcousticPro Professional Mic',
      description: 'High-quality USB condenser mic perfect for recording podcasts, streaming games, and voiceovers.',
      price: 7999,
      discount: 8,
      stock: 12,
      brand: 'AcousticPro',
      images: ['https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'electronics',
    },
    {
      name: 'AcousticPro Pocket Speaker',
      description: 'Ultra-portable mini bluetooth speaker with surprisingly loud volume and 10 hours battery runtime.',
      price: 1299,
      discount: 10,
      stock: 80,
      brand: 'AcousticPro',
      images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'electronics',
    },
    {
      name: 'AcousticPro Active Earphones',
      description: 'In-ear sports earphones with earhooks, sweatproof coating, and crystal-clear stereo calling.',
      price: 2499,
      discount: 15,
      stock: 55,
      brand: 'AcousticPro',
      images: ['https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'electronics',
    },
    {
      name: 'AcousticPro Reference Monitors',
      description: 'Desktop active studio reference monitor speakers for accurate sound engineering and playback.',
      price: 22999,
      discount: 0,
      stock: 10,
      brand: 'AcousticPro',
      images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'electronics',
    },

    // FitVibe (Electronics)
    {
      name: 'FitVibe Smartwatch Active',
      description: 'Modern smartwatch with real-time heart rate monitoring, built-in GPS, custom watchfaces, and sports modes.',
      price: 11999,
      discount: 10,
      stock: 50,
      brand: 'FitVibe',
      images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80'],
      isFeatured: true,
      isTrending: true,
      categorySlug: 'electronics',
    },
    {
      name: 'FitVibe Fitness Tracker Band',
      description: 'Slim wellness band with sleep score analyzer, steps tracker, and calls notification alert system.',
      price: 2499,
      discount: 15,
      stock: 110,
      brand: 'FitVibe',
      images: ['https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: true,
      categorySlug: 'electronics',
    },
    {
      name: 'FitVibe Sports GPS Watch',
      description: 'Premium multisport watch with compass, barometric altimeter, and rugged shockproof structural shell.',
      price: 17999,
      discount: 8,
      stock: 30,
      brand: 'FitVibe',
      images: ['https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&auto=format&fit=crop&q=80'],
      isFeatured: true,
      isTrending: false,
      categorySlug: 'electronics',
    },
    {
      name: 'FitVibe Smart Tracker Ring',
      description: 'Elegant wellness ring crafted from titanium. Tracks temperature, heart rate, and steps discreetly.',
      price: 14999,
      discount: 5,
      stock: 20,
      brand: 'FitVibe',
      images: ['https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'electronics',
    },
    {
      name: 'FitVibe Heart Rate Monitor Band',
      description: 'Chest strap pulse monitor with high precision bluetooth and ANT+ data broadcasting channels.',
      price: 3499,
      discount: 0,
      stock: 45,
      brand: 'FitVibe',
      images: ['https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'electronics',
    },
    {
      name: 'FitVibe Hybrid Smartwatch',
      description: 'Classic physical clock watchhands merged with a stealth digital notification subscreen.',
      price: 13999,
      discount: 10,
      stock: 25,
      brand: 'FitVibe',
      images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'electronics',
    },
    {
      name: 'FitVibe Rugged Sports Watch',
      description: 'Built for high durability outdoors. 100m water resistant casing with standard multi-day backup battery.',
      price: 19999,
      discount: 12,
      stock: 18,
      brand: 'FitVibe',
      images: ['https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'electronics',
    },
    {
      name: 'FitVibe Kids Activity Band',
      description: 'Brightly colored, durable tracker with gamified goals and secure parent dashboard monitoring.',
      price: 1999,
      discount: 20,
      stock: 90,
      brand: 'FitVibe',
      images: ['https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'electronics',
    },
    {
      name: 'FitVibe Smart Tracker Slim',
      description: 'Ultra-thin fitness bracelet focusing on core vitals monitoring and lightweight comfortable styling.',
      price: 2999,
      discount: 10,
      stock: 75,
      brand: 'FitVibe',
      images: ['https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'electronics',
    },
    {
      name: 'FitVibe Luxury Smartwatch',
      description: 'Gold-plated premium watch frame with high definition AMOLED screen and custom designer watch straps.',
      price: 27999,
      discount: 15,
      stock: 8,
      brand: 'FitVibe',
      images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'electronics',
    },

    // StepUp (Fashion)
    {
      name: 'StepUp Canvas Sneakers',
      description: 'Clean everyday canvas shoes featuring soft ortholite inner lining and durable vulcanized rubber soles.',
      price: 3499,
      discount: 10,
      stock: 85,
      brand: 'StepUp',
      images: ['https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: true,
      categorySlug: 'fashion',
    },
    {
      name: 'StepUp Pro Running Shoes',
      description: 'Lightweight mesh upper coupled with energetic response foam cushioning designed for standard runner trails.',
      price: 6999,
      discount: 15,
      stock: 40,
      brand: 'StepUp',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80'],
      isFeatured: true,
      isTrending: true,
      categorySlug: 'fashion',
    },
    {
      name: 'StepUp Classic Suede Loafers',
      description: 'Handcrafted slip-on loafers created from fine suede leather. Adds a smart look to casual suits.',
      price: 4499,
      discount: 5,
      stock: 35,
      brand: 'StepUp',
      images: ['https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'fashion',
    },
    {
      name: 'StepUp Leather Boots',
      description: 'Tough ankle-high leather boots with heavy traction rubber outsoles for rough winter roads.',
      price: 7999,
      discount: 20,
      stock: 25,
      brand: 'StepUp',
      images: ['https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'fashion',
    },
    {
      name: 'StepUp Everyday Slip-ons',
      description: 'Super-flexible mesh knit walkwear shoes. Slide in and out effortlessly without laces.',
      price: 2499,
      discount: 0,
      stock: 95,
      brand: 'StepUp',
      images: ['https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'fashion',
    },
    {
      name: 'StepUp Skate High-Tops',
      description: 'Durable flat-bottom high-top shoes featuring double stitched canvas layers and supportive ankle wraps.',
      price: 3999,
      discount: 10,
      stock: 50,
      brand: 'StepUp',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'fashion',
    },
    {
      name: 'StepUp Summer Sandals',
      description: 'Ergonomic cork-bed sandals with dual adjustable buckle straps. Great for hot weather walks.',
      price: 1799,
      discount: 12,
      stock: 70,
      brand: 'StepUp',
      images: ['https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'fashion',
    },
    {
      name: 'StepUp Knit Trainers',
      description: 'Breathable elastic sock-fit training sneakers with standard foam footbeds for light gym setups.',
      price: 3299,
      discount: 8,
      stock: 60,
      brand: 'StepUp',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'fashion',
    },
    {
      name: 'StepUp Trail Running Shoes',
      description: 'Waterproof outer membrane with high-traction lug soles designed for hiking and cross country routes.',
      price: 5999,
      discount: 15,
      stock: 30,
      brand: 'StepUp',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'fashion',
    },
    {
      name: 'StepUp Formal Derby Shoes',
      description: 'Glossy polished full-grain leather dress shoes. Timeless formal laces fit for wedding event suits.',
      price: 8999,
      discount: 0,
      stock: 20,
      brand: 'StepUp',
      images: ['https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'fashion',
    },

    // VogueStyles (Fashion)
    {
      name: 'VogueStyles Bomber Leather Jacket',
      description: 'Classic fit premium jacket created using 100% genuine lambskin leather. Timeless style.',
      price: 11999,
      discount: 10,
      stock: 15,
      brand: 'VogueStyles',
      images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&auto=format&fit=crop&q=80'],
      isFeatured: true,
      isTrending: true,
      categorySlug: 'fashion',
    },
    {
      name: 'VogueStyles Denim Utility Jacket',
      description: 'Heavyweight cotton blue jean jacket featuring reinforced pocket seams and classic metal snap buttons.',
      price: 3299,
      discount: 15,
      stock: 55,
      brand: 'VogueStyles',
      images: ['https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: true,
      categorySlug: 'fashion',
    },
    {
      name: 'VogueStyles Casual Knit Blazer',
      description: 'Comfortable textured knit stretch fabric blazer. Ideal layer to dress up basic plain shirts.',
      price: 5499,
      discount: 8,
      stock: 28,
      brand: 'VogueStyles',
      images: ['https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&auto=format&fit=crop&q=80'],
      isFeatured: true,
      isTrending: false,
      categorySlug: 'fashion',
    },
    {
      name: 'VogueStyles Oversized Fleece Hoodie',
      description: 'Extra thick brushed inner cotton lining provides a very cozy warm lounge clothing profile.',
      price: 2299,
      discount: 20,
      stock: 80,
      brand: 'VogueStyles',
      images: ['https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'fashion',
    },
    {
      name: 'VogueStyles Tailored Linen Shirt',
      description: 'Lightweight linen blend breathable summer wear shirt. Keeps you cool in hot environments.',
      price: 1899,
      discount: 5,
      stock: 65,
      brand: 'VogueStyles',
      images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'fashion',
    },
    {
      name: 'VogueStyles Premium Trench Coat',
      description: 'Double-breasted classic wool-blend trench coat. Essential winter outer layer for professionals.',
      price: 13999,
      discount: 10,
      stock: 12,
      brand: 'VogueStyles',
      images: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'fashion',
    },
    {
      name: 'VogueStyles Cozy Cable Knit Sweater',
      description: 'Beautiful traditional knit pattern sweater crafted from soft premium acrylic blend yarns.',
      price: 2799,
      discount: 15,
      stock: 40,
      brand: 'VogueStyles',
      images: ['https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'fashion',
    },
    {
      name: 'VogueStyles Slim Fit Chinos',
      description: 'Smart flat-front stretch twill pants. Versatile look for offices and dinner dates alike.',
      price: 2199,
      discount: 12,
      stock: 50,
      brand: 'VogueStyles',
      images: ['https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'fashion',
    },
    {
      name: 'VogueStyles Cotton Casual Shorts',
      description: 'Breathable draw-string loop shorts. Ultimate comfort outfit for beach days and weekends.',
      price: 1299,
      discount: 10,
      stock: 90,
      brand: 'VogueStyles',
      images: ['https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'fashion',
    },
    {
      name: 'VogueStyles Genuine Suede Overcoat',
      description: 'Premium knee-length coat built from soft-brushed suede leather. Elegant high luxury fashion.',
      price: 17999,
      discount: 5,
      stock: 6,
      brand: 'VogueStyles',
      images: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'fashion',
    },

    // BaristaCo (Home & Kitchen)
    {
      name: 'BaristaCo Premium Espresso Maker',
      description: 'Top-tier home espresso station with 15 bar pressure, steam wand, and automatic dosing logic.',
      price: 27999,
      discount: 10,
      stock: 12,
      brand: 'BaristaCo',
      images: ['https://images.unsplash.com/photo-1517256064527-09c53b2d0bc6?w=600&auto=format&fit=crop&q=80'],
      isFeatured: true,
      isTrending: true,
      categorySlug: 'home-kitchen',
    },
    {
      name: 'BaristaCo Conical Burr Grinder',
      description: 'Precision coffee grinder with 40 distinct macro settings for coarse frenchpress to fine espresso.',
      price: 4499,
      discount: 15,
      stock: 35,
      brand: 'BaristaCo',
      images: ['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: true,
      categorySlug: 'home-kitchen',
    },
    {
      name: 'BaristaCo Automatic Milk Frother',
      description: 'Hot and cold milk texturing. Indulge in thick luxurious foam layer caps for cafe lattes.',
      price: 2799,
      discount: 5,
      stock: 50,
      brand: 'BaristaCo',
      images: ['https://images.unsplash.com/photo-1517256064527-09c53b2d0bc6?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'home-kitchen',
    },
    {
      name: 'BaristaCo Gooseneck Drip Kettle',
      description: 'Elegant matte black gooseneck kettle. Features built-in analog thermometer on the lid.',
      price: 3299,
      discount: 20,
      stock: 20,
      brand: 'BaristaCo',
      images: ['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'home-kitchen',
    },
    {
      name: 'BaristaCo Cold Brew Pitcher',
      description: 'Heavy duty borosilicate glass pitcher with fine mesh metal filter core for steeping grounds.',
      price: 1899,
      discount: 0,
      stock: 80,
      brand: 'BaristaCo',
      images: ['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'home-kitchen',
    },
    {
      name: 'BaristaCo French Press Travel',
      description: 'Double walled vacuum insulated travel mug built with an integrated plunger screen mechanism.',
      price: 1499,
      discount: 10,
      stock: 65,
      brand: 'BaristaCo',
      images: ['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'home-kitchen',
    },
    {
      name: 'BaristaCo Drip Brewer Machine',
      description: 'Programmable multi-cup drip brewer. Warm plate functionality ensures fresh hot cups all morning.',
      price: 5999,
      discount: 12,
      stock: 18,
      brand: 'BaristaCo',
      images: ['https://images.unsplash.com/photo-1517256064527-09c53b2d0bc6?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'home-kitchen',
    },
    {
      name: 'BaristaCo Precision Digital Scale',
      description: 'High accuracy food and coffee brewing scale featuring integrated autotimers and tare features.',
      price: 2199,
      discount: 8,
      stock: 40,
      brand: 'BaristaCo',
      images: ['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'home-kitchen',
    },
    {
      name: 'BaristaCo Siphon Coffee Brewer',
      description: 'Stunning science-lab style vacuum siphon coffee maker. Produces clean complex flavor notes.',
      price: 4999,
      discount: 15,
      stock: 15,
      brand: 'BaristaCo',
      images: ['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'home-kitchen',
    },
    {
      name: 'BaristaCo Premium Mug Set',
      description: 'Set of four double-wall thermal insulated glass mugs. Keeps hands cool and espresso hot.',
      price: 2499,
      discount: 0,
      stock: 50,
      brand: 'BaristaCo',
      images: ['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'home-kitchen',
    },

    // GlowRx (Beauty)
    {
      name: 'GlowRx Hyaluronic Face Serum',
      description: 'Intense hydration serum featuring pure hyaluronic acid, organic extract, and vitamin B5.',
      price: 1399,
      discount: 10,
      stock: 65,
      brand: 'GlowRx',
      images: ['https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'beauty',
    },
    {
      name: 'GlowRx Ultra Hydrating Cream',
      description: 'Rich cream focusing on reinforcing weak moisture barriers. Locks skin hydration for 24 hours.',
      price: 1899,
      discount: 15,
      stock: 50,
      brand: 'GlowRx',
      images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80'],
      isFeatured: true,
      isTrending: true,
      categorySlug: 'beauty',
    },
    {
      name: 'GlowRx Sunscreen SPF 50 Matte',
      description: 'Broad spectrum gel block sunscreen. Non-greasy matte finish leaves no chalky white cast.',
      price: 899,
      discount: 5,
      stock: 120,
      brand: 'GlowRx',
      images: ['https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: true,
      categorySlug: 'beauty',
    },
    {
      name: 'GlowRx Amino Gentle Cleanser',
      description: 'Gentle pH-balanced foaming face wash with amino acids. Cleans without stripping skin oils.',
      price: 799,
      discount: 20,
      stock: 95,
      brand: 'GlowRx',
      images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'beauty',
    },
    {
      name: 'GlowRx Anti-Aging Retinol Cream',
      description: 'Encapsulated retinol complex cream. Visibly reduces fine lines and improves skin turnover.',
      price: 2299,
      discount: 0,
      stock: 40,
      brand: 'GlowRx',
      images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'beauty',
    },
    {
      name: 'GlowRx Vitamin C Brightening Mask',
      description: 'Clay mask infused with stable Vitamin C esters and kaolin clay. Unclogs pores and brightens skin.',
      price: 1199,
      discount: 10,
      stock: 60,
      brand: 'GlowRx',
      images: ['https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'beauty',
    },
    {
      name: 'GlowRx Niacinamide Oil Serum',
      description: '10% Niacinamide + 1% Zinc PCA serum. Shrinks enlarged pores and minimizes breakout marks.',
      price: 1299,
      discount: 12,
      stock: 75,
      brand: 'GlowRx',
      images: ['https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'beauty',
    },
    {
      name: 'GlowRx Exfoliating Face Scrub',
      description: 'Extremely fine micro-dermabrasion particles smoothly buff away flaky layers of dead skin.',
      price: 749,
      discount: 8,
      stock: 80,
      brand: 'GlowRx',
      images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'beauty',
    },
    {
      name: 'GlowRx Under Eye Gel Pro',
      description: 'Soothing cooling caffeine peptide eye gel. Instantly depuffs dark circles and fatigue bags.',
      price: 1599,
      discount: 15,
      stock: 45,
      brand: 'GlowRx',
      images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'beauty',
    },
    {
      name: 'GlowRx Recovery Night Oil',
      description: 'Luxury squalane and jojoba sleep oil. Nourishes skin cells deeply to restore bounce by morning.',
      price: 2999,
      discount: 5,
      stock: 30,
      brand: 'GlowRx',
      images: ['https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'beauty',
    },

    // Penguin Books (Books)
    {
      name: 'Atomic Habits (James Clear)',
      description: 'An easy & proven way to build good habits and break bad ones. The definitive self-improvement guide.',
      price: 599,
      discount: 10,
      stock: 120,
      brand: 'Penguin Books',
      images: ['https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&auto=format&fit=crop&q=80'],
      isFeatured: true,
      isTrending: true,
      categorySlug: 'books',
    },
    {
      name: 'Thinking, Fast and Slow (Daniel Kahneman)',
      description: 'Explores the two systems that drive our choices: fast intuitive thinking, and slow logical processing.',
      price: 699,
      discount: 15,
      stock: 80,
      brand: 'Penguin Books',
      images: ['https://images.unsplash.com/photo-1495640388908-05fa85288e61?w=600&auto=format&fit=crop&q=80'],
      isFeatured: true,
      isTrending: false,
      categorySlug: 'books',
    },
    {
      name: 'The Power of Habit (Charles Duhigg)',
      description: 'An award-winning science reporter explains why habits exist and how they can be modified.',
      price: 499,
      discount: 5,
      stock: 95,
      brand: 'Penguin Books',
      images: ['https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: true,
      categorySlug: 'books',
    },
    {
      name: 'Clean Code (Robert C. Martin)',
      description: 'A handbook of agile software craftsmanship. Teaches software developers how to write clean code.',
      price: 2499,
      discount: 20,
      stock: 50,
      brand: 'Penguin Books',
      images: ['https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'books',
    },
    {
      name: 'The Pragmatic Programmer (Andy Hunt)',
      description: 'Essential handbook detailing standard coding practices, architectural structures, and developer mindsets.',
      price: 2999,
      discount: 0,
      stock: 45,
      brand: 'Penguin Books',
      images: ['https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'books',
    },
    {
      name: 'Introduction to Algorithms (CLRS)',
      description: 'The global standard textbook providing thorough analyses and implementations of fundamental computing algorithms.',
      price: 4999,
      discount: 10,
      stock: 30,
      brand: 'Penguin Books',
      images: ['https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'books',
    },
    {
      name: 'Zero to One (Peter Thiel)',
      description: 'Notes on startups, or how to build the future. Legendary builder shares insights on creating unique value.',
      price: 449,
      discount: 12,
      stock: 150,
      brand: 'Penguin Books',
      images: ['https://images.unsplash.com/photo-1495640388908-05fa85288e61?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'books',
    },
    {
      name: 'Start with Why (Simon Sinek)',
      description: 'How great leaders inspire everyone to take action by starting with the fundamental purpose behind operations.',
      price: 499,
      discount: 8,
      stock: 105,
      brand: 'Penguin Books',
      images: ['https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'books',
    },
    {
      name: 'Deep Work (Cal Newport)',
      description: 'Rules for focused success in a distracted world. Master complex skills and produce top level output.',
      price: 549,
      discount: 15,
      stock: 115,
      brand: 'Penguin Books',
      images: ['https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'books',
    },
    {
      name: 'Sapiens (Yuval Noah Harari)',
      description: 'A brief history of humankind. Examines the cognitive, agricultural, and scientific milestones of our species.',
      price: 799,
      discount: 5,
      stock: 90,
      brand: 'Penguin Books',
      images: ['https://images.unsplash.com/photo-1495640388908-05fa85288e61?w=600&auto=format&fit=crop&q=80'],
      isFeatured: false,
      isTrending: false,
      categorySlug: 'books',
    },
  ];

  const productsData = rawProducts.map((p) => {
    const discount = p.discount || 0;
    const discountPrice = p.price - (p.price * discount) / 100;
    return {
      name: p.name,
      description: p.description,
      price: parseFloat(p.price.toFixed(2)),
      discount: parseFloat(discount.toFixed(2)),
      discountPrice: parseFloat(discountPrice.toFixed(2)),
      stock: p.stock,
      brand: p.brand,
      images: p.images,
      isFeatured: p.isFeatured,
      isTrending: p.isTrending,
      categoryId: categories[p.categorySlug].id,
    };
  });

  for (const prod of productsData) {
    await prisma.product.create({
      data: prod,
    });
  }
  console.log('Created products');

  // 6. Create Coupons
  await prisma.coupon.createMany({
    data: [
      {
        code: 'WELCOME10',
        discountType: DiscountType.PERCENTAGE,
        discountValue: 10,
        minCartValue: 3999.00,
        expiryDate: new Date('2030-12-31'),
        isActive: true,
      },
      {
        code: 'FLAT500',
        discountType: DiscountType.FLAT,
        discountValue: 500,
        minCartValue: 9999.00,
        expiryDate: new Date('2030-12-31'),
        isActive: true,
      },
    ],
  });
  console.log('Created active coupons');

  // 7. Create some dummy reviews
  const headphones = await prisma.product.findFirst({
    where: { name: { contains: 'Headphones' } },
  });

  if (headphones) {
    await prisma.review.create({
      data: {
        rating: 5,
        comment: 'Amazing sound quality and very comfortable to wear for long working hours. Noise cancellation is top notch!',
        userId: customer.id,
        productId: headphones.id,
      },
    });

    // Update product average rating
    await prisma.product.update({
      where: { id: headphones.id },
      data: { rating: 5.0 },
    });
  }

  console.log('Seeding completed successfully!');
}

main()
  .catch((e) => {
    console.error('Error during seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
